name: update website

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 2-5'  # Run at 8:30 PM CT Mon-Fri (or 7:30 PM if clocks move forward)
    - cron: '30 22 * * 6,0'  # Run at 4:30 PM CT Sat/Sun (or 3:30 PM if clocks move forward)

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update database
        run: python app/update_database.py
      - name: Update website
        run: python app/update_website.py
      - name: Commit report
        run: |
          git config --global user.name 'Avinash Gupta'
          git config --global user.email 'aviguptatx@gmail.com'
          git commit -am "Automated website update"
          git push
